source 'http://rubygems.org'

# Run your project as following
# > bundle install
# > bundle exec cucumber

# LapisLazul itself
gem 'lapis_lazuli', "2.1.4"

# Allure Cucumber
gem 'allure-cucumber'

# Faker
gem 'faker'

# activesupport
gem 'activesupport'

# httparty
gem 'httparty'